#############################################################################
# Makefile for building: dork
# Generated by qmake (2.01a) (Qt 4.7.3) on: So 28. Aug 22:45:30 2011
# Project:  dork.pro
# Template: subdirs
# Command: c:\QtSDK\Desktop\Qt\4.7.3\mingw\bin\qmake.exe -o Makefile dork.pro
#############################################################################

first: make_default
MAKEFILE      = Makefile
QMAKE         = c:\QtSDK\Desktop\Qt\4.7.3\mingw\bin\qmake.exe
DEL_FILE      = del
CHK_DIR_EXISTS= if not exist
MKDIR         = mkdir
COPY          = copy /y
COPY_FILE     = $(COPY)
COPY_DIR      = xcopy /s /q /y /i
INSTALL_FILE  = $(COPY_FILE)
INSTALL_PROGRAM = $(COPY_FILE)
INSTALL_DIR   = $(COPY_DIR)
DEL_FILE      = del
SYMLINK       = 
DEL_DIR       = rmdir
MOVE          = move
CHK_DIR_EXISTS= if not exist
MKDIR         = mkdir
SUBTARGETS    =  \
		sub-src \
		sub-tests

src\$(MAKEFILE): 
	@$(CHK_DIR_EXISTS) src\ $(MKDIR) src\ 
	cd src\ && $(QMAKE) c:\projekte\dork\src\src.pro -o $(MAKEFILE)
sub-src-qmake_all:  FORCE
	@$(CHK_DIR_EXISTS) src\ $(MKDIR) src\ 
	cd src\ && $(QMAKE) c:\projekte\dork\src\src.pro -o $(MAKEFILE)
sub-src: src\$(MAKEFILE) FORCE
	cd src\ && $(MAKE) -f $(MAKEFILE)
sub-src-make_default: src\$(MAKEFILE) FORCE
	cd src\ && $(MAKE) -f $(MAKEFILE) 
sub-src-make_first: src\$(MAKEFILE) FORCE
	cd src\ && $(MAKE) -f $(MAKEFILE) first
sub-src-all: src\$(MAKEFILE) FORCE
	cd src\ && $(MAKE) -f $(MAKEFILE) all
sub-src-clean: src\$(MAKEFILE) FORCE
	cd src\ && $(MAKE) -f $(MAKEFILE) clean
sub-src-distclean: src\$(MAKEFILE) FORCE
	cd src\ && $(MAKE) -f $(MAKEFILE) distclean
sub-src-install_subtargets: src\$(MAKEFILE) FORCE
	cd src\ && $(MAKE) -f $(MAKEFILE) install
sub-src-uninstall_subtargets: src\$(MAKEFILE) FORCE
	cd src\ && $(MAKE) -f $(MAKEFILE) uninstall
tests\$(MAKEFILE): 
	@$(CHK_DIR_EXISTS) tests\ $(MKDIR) tests\ 
	cd tests\ && $(QMAKE) c:\projekte\dork\tests\tests.pro -o $(MAKEFILE)
sub-tests-qmake_all:  FORCE
	@$(CHK_DIR_EXISTS) tests\ $(MKDIR) tests\ 
	cd tests\ && $(QMAKE) c:\projekte\dork\tests\tests.pro -o $(MAKEFILE)
sub-tests: tests\$(MAKEFILE) FORCE
	cd tests\ && $(MAKE) -f $(MAKEFILE)
sub-tests-make_default: tests\$(MAKEFILE) FORCE
	cd tests\ && $(MAKE) -f $(MAKEFILE) 
sub-tests-make_first: tests\$(MAKEFILE) FORCE
	cd tests\ && $(MAKE) -f $(MAKEFILE) first
sub-tests-all: tests\$(MAKEFILE) FORCE
	cd tests\ && $(MAKE) -f $(MAKEFILE) all
sub-tests-clean: tests\$(MAKEFILE) FORCE
	cd tests\ && $(MAKE) -f $(MAKEFILE) clean
sub-tests-distclean: tests\$(MAKEFILE) FORCE
	cd tests\ && $(MAKE) -f $(MAKEFILE) distclean
sub-tests-install_subtargets: tests\$(MAKEFILE) FORCE
	cd tests\ && $(MAKE) -f $(MAKEFILE) install
sub-tests-uninstall_subtargets: tests\$(MAKEFILE) FORCE
	cd tests\ && $(MAKE) -f $(MAKEFILE) uninstall

Makefile: dork.pro  ../../QtSDK/Desktop/Qt/4.7.3/mingw/mkspecs/default/qmake.conf ../../QtSDK/Desktop/Qt/4.7.3/mingw/mkspecs/qconfig.pri \
		../../QtSDK/Desktop/Qt/4.7.3/mingw/mkspecs/modules/qt_webkit_version.pri \
		../../QtSDK/Desktop/Qt/4.7.3/mingw/mkspecs/features/qt_functions.prf \
		../../QtSDK/Desktop/Qt/4.7.3/mingw/mkspecs/features/qt_config.prf \
		../../QtSDK/Desktop/Qt/4.7.3/mingw/mkspecs/features/exclusive_builds.prf \
		../../QtSDK/Desktop/Qt/4.7.3/mingw/mkspecs/features/default_pre.prf \
		../../QtSDK/Desktop/Qt/4.7.3/mingw/mkspecs/features/win32/default_pre.prf \
		../../QtSDK/Desktop/Qt/4.7.3/mingw/mkspecs/features/debug.prf \
		../../QtSDK/Desktop/Qt/4.7.3/mingw/mkspecs/features/debug_and_release.prf \
		../../QtSDK/Desktop/Qt/4.7.3/mingw/mkspecs/features/default_post.prf \
		../../QtSDK/Desktop/Qt/4.7.3/mingw/mkspecs/features/win32/default_post.prf \
		../../QtSDK/Desktop/Qt/4.7.3/mingw/mkspecs/features/win32/rtti.prf \
		../../QtSDK/Desktop/Qt/4.7.3/mingw/mkspecs/features/win32/exceptions.prf \
		../../QtSDK/Desktop/Qt/4.7.3/mingw/mkspecs/features/win32/stl.prf \
		../../QtSDK/Desktop/Qt/4.7.3/mingw/mkspecs/features/shared.prf \
		../../QtSDK/Desktop/Qt/4.7.3/mingw/mkspecs/features/warn_on.prf \
		../../QtSDK/Desktop/Qt/4.7.3/mingw/mkspecs/features/qt.prf \
		../../QtSDK/Desktop/Qt/4.7.3/mingw/mkspecs/features/win32/thread.prf \
		../../QtSDK/Desktop/Qt/4.7.3/mingw/mkspecs/features/moc.prf \
		../../QtSDK/Desktop/Qt/4.7.3/mingw/mkspecs/features/win32/windows.prf \
		../../QtSDK/Desktop/Qt/4.7.3/mingw/mkspecs/features/resources.prf \
		../../QtSDK/Desktop/Qt/4.7.3/mingw/mkspecs/features/uic.prf \
		../../QtSDK/Desktop/Qt/4.7.3/mingw/mkspecs/features/yacc.prf \
		../../QtSDK/Desktop/Qt/4.7.3/mingw/mkspecs/features/lex.prf \
		../../QtSDK/Desktop/Qt/4.7.3/mingw/mkspecs/features/include_source_dir.prf
	$(QMAKE) -o Makefile dork.pro
..\..\QtSDK\Desktop\Qt\4.7.3\mingw\mkspecs\qconfig.pri:
..\..\QtSDK\Desktop\Qt\4.7.3\mingw\mkspecs\modules\qt_webkit_version.pri:
..\..\QtSDK\Desktop\Qt\4.7.3\mingw\mkspecs\features\qt_functions.prf:
..\..\QtSDK\Desktop\Qt\4.7.3\mingw\mkspecs\features\qt_config.prf:
..\..\QtSDK\Desktop\Qt\4.7.3\mingw\mkspecs\features\exclusive_builds.prf:
..\..\QtSDK\Desktop\Qt\4.7.3\mingw\mkspecs\features\default_pre.prf:
..\..\QtSDK\Desktop\Qt\4.7.3\mingw\mkspecs\features\win32\default_pre.prf:
..\..\QtSDK\Desktop\Qt\4.7.3\mingw\mkspecs\features\debug.prf:
..\..\QtSDK\Desktop\Qt\4.7.3\mingw\mkspecs\features\debug_and_release.prf:
..\..\QtSDK\Desktop\Qt\4.7.3\mingw\mkspecs\features\default_post.prf:
..\..\QtSDK\Desktop\Qt\4.7.3\mingw\mkspecs\features\win32\default_post.prf:
..\..\QtSDK\Desktop\Qt\4.7.3\mingw\mkspecs\features\win32\rtti.prf:
..\..\QtSDK\Desktop\Qt\4.7.3\mingw\mkspecs\features\win32\exceptions.prf:
..\..\QtSDK\Desktop\Qt\4.7.3\mingw\mkspecs\features\win32\stl.prf:
..\..\QtSDK\Desktop\Qt\4.7.3\mingw\mkspecs\features\shared.prf:
..\..\QtSDK\Desktop\Qt\4.7.3\mingw\mkspecs\features\warn_on.prf:
..\..\QtSDK\Desktop\Qt\4.7.3\mingw\mkspecs\features\qt.prf:
..\..\QtSDK\Desktop\Qt\4.7.3\mingw\mkspecs\features\win32\thread.prf:
..\..\QtSDK\Desktop\Qt\4.7.3\mingw\mkspecs\features\moc.prf:
..\..\QtSDK\Desktop\Qt\4.7.3\mingw\mkspecs\features\win32\windows.prf:
..\..\QtSDK\Desktop\Qt\4.7.3\mingw\mkspecs\features\resources.prf:
..\..\QtSDK\Desktop\Qt\4.7.3\mingw\mkspecs\features\uic.prf:
..\..\QtSDK\Desktop\Qt\4.7.3\mingw\mkspecs\features\yacc.prf:
..\..\QtSDK\Desktop\Qt\4.7.3\mingw\mkspecs\features\lex.prf:
..\..\QtSDK\Desktop\Qt\4.7.3\mingw\mkspecs\features\include_source_dir.prf:
qmake: qmake_all FORCE
	@$(QMAKE) -o Makefile dork.pro

qmake_all: sub-src-qmake_all sub-tests-qmake_all FORCE

make_default: sub-src-make_default sub-tests-make_default FORCE
make_first: sub-src-make_first sub-tests-make_first FORCE
all: sub-src-all sub-tests-all FORCE
clean: sub-src-clean sub-tests-clean FORCE
distclean: sub-src-distclean sub-tests-distclean FORCE
	-$(DEL_FILE) Makefile
install_subtargets: sub-src-install_subtargets sub-tests-install_subtargets FORCE
uninstall_subtargets: sub-src-uninstall_subtargets sub-tests-uninstall_subtargets FORCE

sub-src-sub_Debug: src\$(MAKEFILE)
	cd src\ && $(MAKE) debug
sub-tests-sub_Debug: tests\$(MAKEFILE)
	cd tests\ && $(MAKE) debug
debug: sub-src-sub_Debug sub-tests-sub_Debug

sub-src-sub_Release: src\$(MAKEFILE)
	cd src\ && $(MAKE) release
sub-tests-sub_Release: tests\$(MAKEFILE)
	cd tests\ && $(MAKE) release
release: sub-src-sub_Release sub-tests-sub_Release

sub-src-check: src\$(MAKEFILE)
	cd src\ && $(MAKE) check
sub-tests-check: tests\$(MAKEFILE)
	cd tests\ && $(MAKE) check
check: sub-src-check sub-tests-check

mocclean: compiler_moc_header_clean compiler_moc_source_clean

mocables: compiler_moc_header_make_all compiler_moc_source_make_all
install: install_subtargets  FORCE

uninstall:  uninstall_subtargets FORCE

FORCE:

